{
 "title": "flashsystem overall perf stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "vdisk_iops",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flashsystem_perf_vdisk_r_io" },
    { "expr": "flashsystem_perf_vdisk_w_io" }
   ]
  },
  {
   "title": "vdisk_bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    { "expr": "flashsystem_perf_vdisk_r_mb" },
    { "expr": "flashsystem_perf_vdisk_w_mb" }
   ]
  },
  {
   "title": "vdisk_latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "flashsystem_perf_vdisk_r_ms" },
    { "expr": "flashsystem_perf_vdisk_w_ms" }
   ]
  },
  {
   "title": "physical_capacity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "flashsystem_perf_physical_capacity"
    },
    {
     "expr": "flashsystem_perf_physical_free_capacity"
    }
   ]
  }
 ]
}