name: iso-ci.yaml

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  release:
    types: [ published ]

jobs:
  precheck-and-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: run tests
      run: |
        make test

    - name: check copyright
      run: |
        make check-copyright

    - name: login to Docker Hub
      # Only if we need to push an image
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Setup for buildx
    - name: set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Debugging information
    - name: docker info
      run: docker info
    - name: buildx inspect
      run: docker buildx inspect
    
    - name: get tag without v
      id: tag
      if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
      uses: battila7/get-version-action@v2

    # Build and (optionally) push the driver image
    - name: build the driver image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/ppc64le,linux/s390x
        # Only push if we are publishing a release
        push: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        # Use a 'dev' tag, that won't be pushed, for non-release builds
        tags: docker.io/ibmcom/ibm-storage-odf-block-driver:${{ steps.tag.outputs.version-without-v || 'dev' }}
